# Generated by Django 4.2.19 on 2025-03-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Continent',
            field=models.CharField(choices=[('AF', 'Африка'), ('AS', 'Азия'), ('EU', 'Европа'), ('NA', 'Северная Америка'), ('SA', 'Южная Америка'), ('OC', 'Океания'), ('AN', 'Антарктида')], default='AS', help_text='Континент, к которому относится страна', max_length=2),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ManyToManyField(help_text='Город тура', related_name='tours', to='api.city'),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ManyToManyField(help_text='Страна тура', related_name='tours', to='api.country'),
        ),
    ]
