# Generated by Django 4.2.19 on 2025-03-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(help_text='Полное имя пользователя', max_length=255, null=True),
        ),
    ]
