# Generated by Django 4.2.19 on 2025-03-08 01:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_country_continent_remove_tour_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Обложка тура', null=True, upload_to='tours/covers/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_days',
            field=models.IntegerField(default=1, help_text='Продолжительность тура в днях'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='map_links',
            field=models.JSONField(default=api.models.default_map_links, help_text='Ссылки на карты'),
        ),
    ]
