# Generated by Django 4.2.19 on 2025-03-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_top',
            field=models.BooleanField(default=True, help_text='Горящие тур или нет', null=True),
        ),
    ]
