# Generated by Django 4.2.19 on 2025-03-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tour_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tour',
        ),
        migrations.AddField(
            model_name='cart',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
    ]
