# Generated by Django 4.2.19 on 2025-03-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cart_tour_cart_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='booking',
        ),
        migrations.AddField(
            model_name='cart',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tour'),
        ),
    ]
