# Generated by Django 4.2.19 on 2025-03-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cart_booking_cart_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(help_text='Название города', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(help_text='Название города', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(help_text='Название страны', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(help_text='Название страны', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='events_en',
            field=models.JSONField(default=list, help_text='Список мероприятий', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='events_ru',
            field=models.JSONField(default=list, help_text='Список мероприятий', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_list_en',
            field=models.TextField(help_text='Цены тура', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_list_ru',
            field=models.TextField(help_text='Цены тура', null=True),
        ),
    ]
